apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: facefeed-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: facefeed
      labels:
        app: facefeed
    spec:
      initContainers:
      - name: elasticsearch-ping
        image: xiiot/facefeed-app:edge_1.12_plus
        command: ['./waitForES.sh']
      containers:
      - name: facefeed
        imagePullPolicy: IfNotPresent
        image: xiiot/facefeed-app:edge_1.12_plus
        ports:
        - containerPort: 8888
        command:
        - sh
        - -c
        - "exec python main.py"
---
kind: Service
apiVersion: v1
metadata:
  name: facefeed-svc
spec:
  selector:
    app: facefeed
  ports:
  - protocol: TCP
    port: 8888
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: facefeed-proxy
spec:
  replicas: 1
  template:
    metadata:
      name: facefeed-proxy
      labels:
        app: facefeed-proxy
    spec:
      containers:
      - name: facefeed-tcp
        image: xiiot/gcr_facefeed:edge_1.12_plus
        args: [ "tcp", "8888", "facefeed-svc" ]
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          protocol: TCP
          containerPort: 8888
          hostPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9200
  selector:
    app: elasticsearch
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox:1.29.3
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'chmod -R 777  /usr/share/elasticsearch/data']
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data

      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
        name: elasticsearch
        imagePullPolicy: IfNotPresent
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: local
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi